# Covertype Data Set Preprocessing

In [1]:
import csv
import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split

### Set the paths

In [2]:
FULL_DATASET = 'covertype.csv'
SMALL_DATASET= 'covertype_small.csv'
TRAINING_DATASET='covertype_training.csv'
TRAINING_DATASET_WITH_MISSING = 'covertype_training_missing.csv'
EVALUATION_DATASET='covertype_evaluation.csv'
EVALUATION_DATASET_WITH_ANOMALIES='covertype_evaluation_anomalies.csv'
SERVING_DATASET='covertype_serving.csv'

ORIGINAL_DATASET_PATH = 'raw/covertype.csv'

## Preprocess the original dataset

### Load the dataset

In [3]:
df = pd.read_csv(ORIGINAL_DATASET_PATH, header=None)
print(df.shape)
df.head()

(581012, 55)

,0,1,2,3,4,5,6,7,8,9,...,45,46,47,48,49,50,51,52,53,54
0,2596,51,3,258,0,510,221,232,148,6279,...,0,0,0,0,0,0,0,0,0,5
1,2590,56,2,212,-6,390,220,235,151,6225,...,0,0,0,0,0,0,0,0,0,5
2,2804,139,9,268,65,3180,234,238,135,6121,...,0,0,0,0,0,0,0,0,0,2
3,2785,155,18,242,118,3090,238,238,122,6211,...,0,0,0,0,0,0,0,0,0,2
4,2595,45,2,153,-1,391,220,234,150,6172,...,0,0,0,0,0,0,0,0,0,5

### Configure soil type and wilderness area domains

In [4]:
soil_type = [
"1", "C2702", "Cathedral family - Rock outcrop complex, extremely stony.",
"2", "C2703", "Vanet - Ratake families complex, very stony.",
"3", "C2704", "Haploborolis - Rock outcrop complex, rubbly.",
"4", "C2705", "Ratake family - Rock outcrop complex, rubbly.",
"5", "C2706", "Vanet family - Rock outcrop complex complex, rubbly.",
"6", "C2717", "Vanet - Wetmore families - Rock outcrop complex, stony.",
"7", "C3501", "Gothic family.",
"8", "C3502", "Supervisor - Limber families complex.",
"9", "C4201", "Troutville family, very stony.",
"10", "C4703", "Bullwark - Catamount families - Rock outcrop complex, rubbly.",
"11", "C4704", "Bullwark - Catamount families - Rock land complex, rubbly.",
"12", "C4744", "Legault family - Rock land complex, stony.",
"13", "C4758", "Catamount family - Rock land - Bullwark family complex, rubbly.",
"14", "C5101", "Pachic Argiborolis - Aquolis complex.",
"15", "C5151", "unspecified in the USFS Soil and ELU Survey.",
"16", "C6101", "Cryaquolis - Cryoborolis complex.",
"17", "C6102", "Gateview family - Cryaquolis complex.",
"18", "C6731", "Rogert family, very stony.",
"19", "C7101", "Typic Cryaquolis - Borohemists complex.",
"20", "C7102", "Typic Cryaquepts - Typic Cryaquolls complex.",
"21", "C7103", "Typic Cryaquolls - Leighcan family, till substratum complex.",
"22", "C7201", "Leighcan family, till substratum, extremely bouldery.",
"23", "C7202", "Leighcan family, till substratum - Typic Cryaquolls complex.",
"24", "C7700", "Leighcan family, extremely stony.",
"25", "C7701", "Leighcan family, warm, extremely stony.",
"26", "C7702", "Granile - Catamount families complex, very stony.",
"27", "C7709", "Leighcan family, warm - Rock outcrop complex, extremely stony.",
"28", "C7710", "Leighcan family - Rock outcrop complex, extremely stony.",
"29", "C7745", "Como - Legault families complex, extremely stony.",
"30", "C7746", "Como family - Rock land - Legault family complex, extremely stony.",
"31", "C7755", "Leighcan - Catamount families complex, extremely stony.",
"32", "C7756", "Catamount family - Rock outcrop - Leighcan family complex, extremely stony.",
"33", "C7757", "Leighcan - Catamount families - Rock outcrop complex, extremely stony.",
"34", "C7790", "Cryorthents - Rock land complex, extremely stony.",
"35", "C8703", "Cryumbrepts - Rock outcrop - Cryaquepts complex.",
"36", "C8707", "Bross family - Rock land - Cryumbrepts complex, extremely stony.",
"37", "C8708", "Rock outcrop - Cryumbrepts - Cryorthents complex, extremely stony.",
"38", "C8771", "Leighcan - Moran families - Cryaquolls complex, extremely stony.",
"39", "C8772", "Moran family - Cryorthents - Leighcan family complex, extremely stony.",
"40", "C8776", "Moran family - Cryorthents - Rock land complex, extremely stony.",
]

wilderness_area = [
"Rawah", "Rawah Wilderness Area",
"Neota", "Neota Wilderness Area",
"Commanche", "Comanche Peak Wilderness Area",
"Cache", "Cache la Poudre Wilderness Area"
]

### Map one-hot encoded values to categorical domains

In [5]:
soil = df.loc[:, 14:53].apply(lambda x: soil_type[1::3][x.to_numpy().nonzero()[0][0]], axis=1)
soil

0         C7745
1         C7745
2         C4744
3         C7746
4         C7745
          ...
581007    C2703
581008    C2703
581009    C2703
581010    C2703
581011    C2703
Length: 581012, dtype: str

In [6]:
wilderness = df.loc[:, 10:13].apply(lambda x: wilderness_area[0::2][x.to_numpy().nonzero()[0][0]], axis=1)
wilderness

0             Rawah
1             Rawah
2             Rawah
3             Rawah
4             Rawah
            ...
581007    Commanche
581008    Commanche
581009    Commanche
581010    Commanche
581011    Commanche
Length: 581012, dtype: str

### Create a dataset with column names and categorical values replacing one-hot encoded soil type and wilderness areas

In [7]:
COLUMN_NAMES = [
    'Elevation', 
    'Aspect', 
    'Slope', 
    'Horizontal_Distance_To_Hydrology',
    'Vertical_Distance_To_Hydrology',
    'Horizontal_Distance_To_Roadways',
    'Hillshade_9am',
    'Hillshade_Noon',
    'Hillshade_3pm',
    'Horizontal_Distance_To_Fire_Points',
    'Wilderness_Area',
    'Soil_Type',
    'Cover_Type']

df_full = pd.concat([df.loc[:, 0:9], wilderness, soil, df.loc[:, 54]], axis=1, ignore_index=True)
df_full.columns = COLUMN_NAMES
df_full

,Elevation,Aspect,Slope,Horizontal_Distance_To_Hydrology,Vertical_Distance_To_Hydrology,Horizontal_Distance_To_Roadways,Hillshade_9am,Hillshade_Noon,Hillshade_3pm,Horizontal_Distance_To_Fire_Points,Wilderness_Area,Soil_Type,Cover_Type
0,2596,51,3,258,0,510,221,232,148,6279,Rawah,C7745,5
1,2590,56,2,212,-6,390,220,235,151,6225,Rawah,C7745,5
2,2804,139,9,268,65,3180,234,238,135,6121,Rawah,C4744,2
3,2785,155,18,242,118,3090,238,238,122,6211,Rawah,C7746,2
4,2595,45,2,153,-1,391,220,234,150,6172,Rawah,C7745,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...
581007,2396,153,20,85,17,108,240,237,118,837,Commanche,C2703,3
581008,2391,152,19,67,12,95,240,237,119,845,Commanche,C2703,3
581009,2386,159,17,60,7,90,236,241,130,854,Commanche,C2703,3
581010,2384,170,15,60,5,90,230,245,143,864,Commanche,C2703,3
581011,2383,165,13,60,4,67,231,244,141,875,Commanche,C2703,3

### Convert the label to 0-6 range

In [8]:
df_full['Cover_Type'] = df_full['Cover_Type'] - 1

### Save the dataset to CSV file

In [9]:
df_full.to_csv(FULL_DATASET, header=True, index=False)

In [10]:
!head $FULL_DATASET

'head' is not recognized as an internal or external command,
operable program or batch file.

## Create training, validation, testing and serving splits.

In [11]:
df_full = df = pd.read_csv(FULL_DATASET, dtype={'Soil_Type': object})
df_full

,Elevation,Aspect,Slope,Horizontal_Distance_To_Hydrology,Vertical_Distance_To_Hydrology,Horizontal_Distance_To_Roadways,Hillshade_9am,Hillshade_Noon,Hillshade_3pm,Horizontal_Distance_To_Fire_Points,Wilderness_Area,Soil_Type,Cover_Type
0,2596,51,3,258,0,510,221,232,148,6279,Rawah,C7745,4
1,2590,56,2,212,-6,390,220,235,151,6225,Rawah,C7745,4
2,2804,139,9,268,65,3180,234,238,135,6121,Rawah,C4744,1
3,2785,155,18,242,118,3090,238,238,122,6211,Rawah,C7746,1
4,2595,45,2,153,-1,391,220,234,150,6172,Rawah,C7745,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...
581007,2396,153,20,85,17,108,240,237,118,837,Commanche,C2703,2
581008,2391,152,19,67,12,95,240,237,119,845,Commanche,C2703,2
581009,2386,159,17,60,7,90,236,241,130,854,Commanche,C2703,2
581010,2384,170,15,60,5,90,230,245,143,864,Commanche,C2703,2
581011,2383,165,13,60,4,67,231,244,141,875,Commanche,C2703,2

In [12]:
df_full.Soil_Type.value_counts()

Soil_Type
C7745    115247
C7202     57752
C7756     52519
C7757     45154
C7201     33373
C4703     32634
C7746     30170
C4744     29971
C7755     25666
C7700     21278
C4758     17431
C8771     15573
C8772     13806
C4704     12410
C2705     12396
C7102      9259
C8776      8750
C2703      7525
C2717      6575
C2704      4823
C7101      4021
C6102      3422
C2702      3031
C6101      2845
C7702      2589
C6731      1899
C8703      1891
C7790      1611
C2706      1597
C4201      1147
C7709      1086
C7710       946
C7103       838
C5101       599
C7701       474
C8708       298
C3502       179
C8707       119
C3501       105
C5151         3
Name: count, dtype: int64

In [13]:
df_5151 = df_full[df_full['Soil_Type']=='C5151']
df_no_5151 = df_full[df_full['Soil_Type']!='C5151']

In [14]:
df_5151

,Elevation,Aspect,Slope,Horizontal_Distance_To_Hydrology,Vertical_Distance_To_Hydrology,Horizontal_Distance_To_Roadways,Hillshade_9am,Hillshade_Noon,Hillshade_3pm,Horizontal_Distance_To_Fire_Points,Wilderness_Area,Soil_Type,Cover_Type
241543,2078,34,10,0,0,212,219,218,134,484,Cache,C5151,5
241544,2080,13,19,30,0,192,198,197,132,499,Cache,C5151,5
241545,2076,27,24,30,5,175,201,180,105,516,Cache,C5151,5

In [15]:
df_no_5151

,Elevation,Aspect,Slope,Horizontal_Distance_To_Hydrology,Vertical_Distance_To_Hydrology,Horizontal_Distance_To_Roadways,Hillshade_9am,Hillshade_Noon,Hillshade_3pm,Horizontal_Distance_To_Fire_Points,Wilderness_Area,Soil_Type,Cover_Type
0,2596,51,3,258,0,510,221,232,148,6279,Rawah,C7745,4
1,2590,56,2,212,-6,390,220,235,151,6225,Rawah,C7745,4
2,2804,139,9,268,65,3180,234,238,135,6121,Rawah,C4744,1
3,2785,155,18,242,118,3090,238,238,122,6211,Rawah,C7746,1
4,2595,45,2,153,-1,391,220,234,150,6172,Rawah,C7745,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...
581007,2396,153,20,85,17,108,240,237,118,837,Commanche,C2703,2
581008,2391,152,19,67,12,95,240,237,119,845,Commanche,C2703,2
581009,2386,159,17,60,7,90,236,241,130,854,Commanche,C2703,2
581010,2384,170,15,60,5,90,230,245,143,864,Commanche,C2703,2
581011,2383,165,13,60,4,67,231,244,141,875,Commanche,C2703,2

In [16]:
df_small, df_other = train_test_split(df_no_5151, train_size=100000, stratify=df_no_5151.Cover_Type)

In [17]:
df_train, df_other = train_test_split(df_no_5151, train_size=431009, stratify=df_no_5151.Cover_Type)
df_evaluate, df_serving = train_test_split(df_other, train_size=75000, stratify=df_other.Cover_Type)
df_serving = df_serving.drop(columns=['Cover_Type'])
print(df_train.shape)
print(df_evaluate.shape)
print(df_serving.shape)

(431009, 13)
(75000, 13)
(75000, 12)

Add some missing values to the training split.

In [18]:
df_train_missing = df_train.reset_index(drop=True)
df_train_missing.loc[0:8999, 'Horizontal_Distance_To_Hydrology'] = None
df_train_missing

,Elevation,Aspect,Slope,Horizontal_Distance_To_Hydrology,Vertical_Distance_To_Hydrology,Horizontal_Distance_To_Roadways,Hillshade_9am,Hillshade_Noon,Hillshade_3pm,Horizontal_Distance_To_Fire_Points,Wilderness_Area,Soil_Type,Cover_Type
0,3182,28,11,NaN,106,630,216,215,134,1788,Commanche,C7757,1
1,3050,347,9,NaN,32,3094,204,226,161,999,Commanche,C7756,1
2,2503,346,23,NaN,22,1642,170,198,162,391,Commanche,C4703,2
3,3213,83,4,NaN,0,2802,225,233,143,725,Rawah,C7202,0
4,2140,47,13,NaN,0,854,224,212,120,1521,Cache,C4703,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...
431004,2695,314,15,95.0,28,1215,177,226,189,1839,Rawah,C7746,1
431005,2974,348,9,1064.0,208,2614,203,225,161,904,Commanche,C7755,1
431006,2724,330,10,256.0,28,2148,196,228,171,2124,Rawah,C7745,1
431007,3012,270,5,212.0,49,443,207,241,173,579,Neota,C7201,1
431008,3241,355,11,558.0,170,3323,201,220,156,1812,Commanche,C7756,0

Create the evaluation split where some values of Slope are more than 90 degrees and 3 examples have 5151 code for soil type, which is not present in the training split.

In [19]:
df_evaluate_anomalies = df_evaluate.reset_index(drop=True)
df_evaluate_anomalies.loc[0:4, 'Slope'] = 110
df_evaluate_anomalies = pd.concat([df_evaluate_anomalies, df_5151])
df_evaluate_anomalies

,Elevation,Aspect,Slope,Horizontal_Distance_To_Hydrology,Vertical_Distance_To_Hydrology,Horizontal_Distance_To_Roadways,Hillshade_9am,Hillshade_Noon,Hillshade_3pm,Horizontal_Distance_To_Fire_Points,Wilderness_Area,Soil_Type,Cover_Type
0,3324,14,110,182,56,3370,207,213,141,1758,Rawah,C8771,0
1,2301,334,110,150,57,1292,165,206,177,459,Cache,C4703,2
2,2932,273,110,190,105,5148,142,236,228,4836,Rawah,C7700,0
3,3208,34,110,150,58,5085,219,225,142,883,Rawah,C7201,0
4,3260,342,110,283,70,1909,164,197,167,1952,Neota,C7757,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
74998,3064,209,26,162,56,828,191,253,184,576,Commanche,C7700,1
74999,2532,198,17,127,41,1084,212,252,169,1234,Commanche,C2705,2
241543,2078,34,10,0,0,212,219,218,134,484,Cache,C5151,5
241544,2080,13,19,30,0,192,198,197,132,499,Cache,C5151,5
241545,2076,27,24,30,5,175,201,180,105,516,Cache,C5151,5

In [20]:
df_evaluate_anomalies.Soil_Type.value_counts()

Soil_Type
C7745    14834
C7202     7346
C7756     6670
C7757     5795
C7201     4326
C4703     4273
C7746     3981
C4744     3836
C7755     3324
C7700     2733
C4758     2266
C8771     1973
C8772     1760
C4704     1641
C2705     1582
C7102     1278
C8776     1151
C2703     1008
C2717      845
C2704      629
C7101      516
C6102      462
C2702      359
C6101      352
C7702      334
C6731      283
C7790      248
C8703      245
C2706      209
C7709      159
C4201      132
C7710      125
C7103      110
C5101       83
C7701       53
C8708       27
C3502       21
C8707       17
C3501       14
C5151        3
Name: count, dtype: int64

### Save the splits to local files.

In [21]:
df_train.to_csv(TRAINING_DATASET, header=True, index=False)
df_small.to_csv(SMALL_DATASET, header=True, index=False)
df_train_missing.to_csv(TRAINING_DATASET_WITH_MISSING, header=True, index=False)
df_evaluate.to_csv(EVALUATION_DATASET, header=True, index=False)
df_evaluate_anomalies.to_csv(EVALUATION_DATASET_WITH_ANOMALIES, header=True, index=False)
df_serving.to_csv(SERVING_DATASET, header=True, index=False)

### Copy the splits to GCS

In [22]:
!gsutil cp $FULL_DATASET gs://workshop-datasets/covertype/full/dataset.csv
!gsutil cp $SMALL_DATASET gs://workshop-datasets/covertype/small/dataset.csv
!gsutil cp $TRAINING_DATASET gs://workshop-datasets/covertype/training/dataset.csv
!gsutil cp $TRAINING_DATASET_WITH_MISSING gs://workshop-datasets/covertype/training_missing/dataset.csv
!gsutil cp $EVALUATION_DATASET gs://workshop-datasets/covertype/evaluation/dataset.csv
!gsutil cp $EVALUATION_DATASET_WITH_ANOMALIES gs://workshop-datasets/covertype/evaluation_anomalies/dataset.csv
!gsutil cp $SERVING_DATASET gs://workshop-datasets/covertype/serving/dataset.csv

^C

Reauthentication required.
Traceback (most recent call last):
  File "C:\Users\dandiazc\AppData\Local\Google\Cloud SDK\google-cloud-sdk\platform\gsutil\gsutil", line 21, in <module>
    gsutil.RunMain()
  File "C:\Users\dandiazc\AppData\Local\Google\Cloud SDK\google-cloud-sdk\platform\gsutil\gsutil.py", line 151, in RunMain
    sys.exit(gslib.__main__.main())
  File "C:\Users\dandiazc\AppData\Local\Google\Cloud SDK\google-cloud-sdk\platform\gsutil\gslib\__main__.py", line 436, in main
    return _RunNamedCommandAndHandleExceptions(
  File "C:\Users\dandiazc\AppData\Local\Google\Cloud SDK\google-cloud-sdk\platform\gsutil\gslib\__main__.py", line 785, in _RunNamedCommandAndHandleExceptions
    _HandleUnknownFailure(e)
  File "C:\Users\dandiazc\AppData\Local\Google\Cloud SDK\google-cloud-sdk\platform\gsutil\gslib\__main__.py", line 633, in _RunNamedCommandAndHandleExceptions
    return command_runner.RunNamedCommand(command_name,
  File "C:\Users\dandiazc\AppData\Local\Google\Cloud SDK\google-cloud-sdk\platform\gsutil\gslib\command_runner.py", line 421, in RunNamedCommand
    return_code = command_inst.RunCommand()
  File "C:\Users\dandiazc\AppData\Local\Google\Cloud SDK\google-cloud-sdk\platform\gsutil\gslib\commands\cp.py", line 1054, in RunCommand
    name_expansion_iterator = CopyObjectsIterator(
  File "C:\Users\dandiazc\AppData\Local\Google\Cloud SDK\google-cloud-sdk\platform\gsutil\gslib\name_expansion.py", line 677, in __init__
    name_expansion_dest_tuple = next(self.name_expansion_dest_iter)
  File "C:\Users\dandiazc\AppData\Local\Google\Cloud SDK\google-cloud-sdk\platform\gsutil\gslib\commands\cp.py", line 985, in _ConstructNameExpansionIteratorDstTupleIterator
    copy_helper.ExpandUrlToSingleBlr(dst_url_str,
  File "C:\Users\dandiazc\AppData\Local\Google\Cloud SDK\google-cloud-sdk\platform\gsutil\gslib\utils\copy_helper.py", line 1457, in ExpandUrlToSingleBlr
    for obj_or_prefix in list_iterator:
  File "C:\Users\dandiazc\AppData\Local\Google\Cloud SDK\google-cloud-sdk\platform\gsutil\gslib\gcs_json_api.py", line 812, in ListObjects
    object_list = self.api_client.objects.List(apitools_request,
  File "C:\Users\dandiazc\AppData\Local\Google\Cloud SDK\google-cloud-sdk\platform\gsutil\gslib\third_party\storage_apitools\storage_v1_client.py", line 1207, in List
    return self._RunMethod(
  File "C:\Users\dandiazc\AppData\Local\Google\Cloud SDK\google-cloud-sdk\platform\gsutil\third_party\apitools\apitools\base\py\base_api.py", line 734, in _RunMethod
    http_response = http_wrapper.MakeRequest(
  File "C:\Users\dandiazc\AppData\Local\Google\Cloud SDK\google-cloud-sdk\platform\gsutil\third_party\apitools\apitools\base\py\http_wrapper.py", line 359, in MakeRequest
    retry_func(ExceptionRetryArgs(http, http_request, e, retry,
  File "C:\Users\dandiazc\AppData\Local\Google\Cloud SDK\google-cloud-sdk\platform\gsutil\gslib\utils\retry_util.py", line 65, in WarnAfterManyRetriesHandler
    http_wrapper.HandleExceptionsAndRebuildHttpConnections(retry_args)
  File "C:\Users\dandiazc\AppData\Local\Google\Cloud SDK\google-cloud-sdk\platform\gsutil\third_party\apitools\apitools\base\py\http_wrapper.py", line 304, in HandleExceptionsAndRebuildHttpConnections
    raise retry_args.exc
  File "C:\Users\dandiazc\AppData\Local\Google\Cloud SDK\google-cloud-sdk\platform\gsutil\third_party\apitools\apitools\base\py\http_wrapper.py", line 348, in MakeRequest
    return _MakeRequestNoRetry(
  File "C:\Users\dandiazc\AppData\Local\Google\Cloud SDK\google-cloud-sdk\platform\gsutil\third_party\apitools\apitools\base\py\http_wrapper.py", line 397, in _MakeRequestNoRetry
    info, content = http.request(
  File "C:\Users\dandiazc\AppData\Local\Google\Cloud SDK\google-cloud-sdk\platform\gsutil\gslib\vendored\oauth2client\oauth2client\transport.py", line 159, in new_request
    credentials._refresh(orig_request_method)
  File "C:\Users\dandiazc\AppData\Local\Google\Cloud SDK\google-cloud-sdk\platform\gsutil\gslib\vendored\oauth2client\oauth2client\client.py", line 761, in _refresh
    self._do_refresh_request(http)
  File "C:\Users\dandiazc\AppData\Local\Google\Cloud SDK\google-cloud-sdk\platform\gsutil\third_party\google-reauth-python\google_reauth\reauth_creds.py", line 112, in _do_refresh_request
    self._update(*reauth.refresh_access_token(
  File "C:\Users\dandiazc\AppData\Local\Google\Cloud SDK\google-cloud-sdk\platform\gsutil\third_party\google-reauth-python\google_reauth\reauth.py", line 283, in refresh_access_token
    rapt = get_rapt_token(
  File "C:\Users\dandiazc\AppData\Local\Google\Cloud SDK\google-cloud-sdk\platform\gsutil\third_party\google-reauth-python\google_reauth\reauth.py", line 194, in get_rapt_token
    rapt_token = _obtain_rapt(
  File "C:\Users\dandiazc\AppData\Local\Google\Cloud SDK\google-cloud-sdk\platform\gsutil\third_party\google-reauth-python\google_reauth\reauth.py", line 142, in _obtain_rapt
    raise errors.ReauthUnattendedError()
google_reauth.errors.ReauthUnattendedError: Reauthentication challenge could not be answered because you are not in an interactive session.
Reauthentication required.
Traceback (most recent call last):
  File "C:\Users\dandiazc\AppData\Local\Google\Cloud SDK\google-cloud-sdk\platform\gsutil\gsutil", line 21, in <module>
    gsutil.RunMain()
  File "C:\Users\dandiazc\AppData\Local\Google\Cloud SDK\google-cloud-sdk\platform\gsutil\gsutil.py", line 151, in RunMain
    sys.exit(gslib.__main__.main())
  File "C:\Users\dandiazc\AppData\Local\Google\Cloud SDK\google-cloud-sdk\platform\gsutil\gslib\__main__.py", line 436, in main
    return _RunNamedCommandAndHandleExceptions(
  File "C:\Users\dandiazc\AppData\Local\Google\Cloud SDK\google-cloud-sdk\platform\gsutil\gslib\__main__.py", line 785, in _RunNamedCommandAndHandleExceptions
    _HandleUnknownFailure(e)
  File "C:\Users\dandiazc\AppData\Local\Google\Cloud SDK\google-cloud-sdk\platform\gsutil\gslib\__main__.py", line 633, in _RunNamedCommandAndHandleExceptions
    return command_runner.RunNamedCommand(command_name,
  File "C:\Users\dandiazc\AppData\Local\Google\Cloud SDK\google-cloud-sdk\platform\gsutil\gslib\command_runner.py", line 421, in RunNamedCommand
    return_code = command_inst.RunCommand()
  File "C:\Users\dandiazc\AppData\Local\Google\Cloud SDK\google-cloud-sdk\platform\gsutil\gslib\commands\cp.py", line 1054, in RunCommand
    name_expansion_iterator = CopyObjectsIterator(
  File "C:\Users\dandiazc\AppData\Local\Google\Cloud SDK\google-cloud-sdk\platform\gsutil\gslib\name_expansion.py", line 677, in __init__
    name_expansion_dest_tuple = next(self.name_expansion_dest_iter)
  File "C:\Users\dandiazc\AppData\Local\Google\Cloud SDK\google-cloud-sdk\platform\gsutil\gslib\commands\cp.py", line 985, in _ConstructNameExpansionIteratorDstTupleIterator
    copy_helper.ExpandUrlToSingleBlr(dst_url_str,
  File "C:\Users\dandiazc\AppData\Local\Google\Cloud SDK\google-cloud-sdk\platform\gsutil\gslib\utils\copy_helper.py", line 1457, in ExpandUrlToSingleBlr
    for obj_or_prefix in list_iterator:
  File "C:\Users\dandiazc\AppData\Local\Google\Cloud SDK\google-cloud-sdk\platform\gsutil\gslib\gcs_json_api.py", line 812, in ListObjects
    object_list = self.api_client.objects.List(apitools_request,
  File "C:\Users\dandiazc\AppData\Local\Google\Cloud SDK\google-cloud-sdk\platform\gsutil\gslib\third_party\storage_apitools\storage_v1_client.py", line 1207, in List
    return self._RunMethod(
  File "C:\Users\dandiazc\AppData\Local\Google\Cloud SDK\google-cloud-sdk\platform\gsutil\third_party\apitools\apitools\base\py\base_api.py", line 734, in _RunMethod
    http_response = http_wrapper.MakeRequest(
  File "C:\Users\dandiazc\AppData\Local\Google\Cloud SDK\google-cloud-sdk\platform\gsutil\third_party\apitools\apitools\base\py\http_wrapper.py", line 359, in MakeRequest
    retry_func(ExceptionRetryArgs(http, http_request, e, retry,
  File "C:\Users\dandiazc\AppData\Local\Google\Cloud SDK\google-cloud-sdk\platform\gsutil\gslib\utils\retry_util.py", line 65, in WarnAfterManyRetriesHandler
    http_wrapper.HandleExceptionsAndRebuildHttpConnections(retry_args)
  File "C:\Users\dandiazc\AppData\Local\Google\Cloud SDK\google-cloud-sdk\platform\gsutil\third_party\apitools\apitools\base\py\http_wrapper.py", line 304, in HandleExceptionsAndRebuildHttpConnections
    raise retry_args.exc
  File "C:\Users\dandiazc\AppData\Local\Google\Cloud SDK\google-cloud-sdk\platform\gsutil\third_party\apitools\apitools\base\py\http_wrapper.py", line 348, in MakeRequest
    return _MakeRequestNoRetry(
  File "C:\Users\dandiazc\AppData\Local\Google\Cloud SDK\google-cloud-sdk\platform\gsutil\third_party\apitools\apitools\base\py\http_wrapper.py", line 397, in _MakeRequestNoRetry
    info, content = http.request(
  File "C:\Users\dandiazc\AppData\Local\Google\Cloud SDK\google-cloud-sdk\platform\gsutil\gslib\vendored\oauth2client\oauth2client\transport.py", line 159, in new_request
    credentials._refresh(orig_request_method)
  File "C:\Users\dandiazc\AppData\Local\Google\Cloud SDK\google-cloud-sdk\platform\gsutil\gslib\vendored\oauth2client\oauth2client\client.py", line 761, in _refresh
    self._do_refresh_request(http)
  File "C:\Users\dandiazc\AppData\Local\Google\Cloud SDK\google-cloud-sdk\platform\gsutil\third_party\google-reauth-python\google_reauth\reauth_creds.py", line 112, in _do_refresh_request
    self._update(*reauth.refresh_access_token(
  File "C:\Users\dandiazc\AppData\Local\Google\Cloud SDK\google-cloud-sdk\platform\gsutil\third_party\google-reauth-python\google_reauth\reauth.py", line 283, in refresh_access_token
    rapt = get_rapt_token(
  File "C:\Users\dandiazc\AppData\Local\Google\Cloud SDK\google-cloud-sdk\platform\gsutil\third_party\google-reauth-python\google_reauth\reauth.py", line 194, in get_rapt_token
    rapt_token = _obtain_rapt(
  File "C:\Users\dandiazc\AppData\Local\Google\Cloud SDK\google-cloud-sdk\platform\gsutil\third_party\google-reauth-python\google_reauth\reauth.py", line 142, in _obtain_rapt
    raise errors.ReauthUnattendedError()
google_reauth.errors.ReauthUnattendedError: Reauthentication challenge could not be answered because you are not in an interactive session.
Reauthentication required.
Traceback (most recent call last):
  File "C:\Users\dandiazc\AppData\Local\Google\Cloud SDK\google-cloud-sdk\platform\gsutil\gsutil", line 21, in <module>
    gsutil.RunMain()
  File "C:\Users\dandiazc\AppData\Local\Google\Cloud SDK\google-cloud-sdk\platform\gsutil\gsutil.py", line 151, in RunMain
    sys.exit(gslib.__main__.main())
  File "C:\Users\dandiazc\AppData\Local\Google\Cloud SDK\google-cloud-sdk\platform\gsutil\gslib\__main__.py", line 436, in main
    return _RunNamedCommandAndHandleExceptions(
  File "C:\Users\dandiazc\AppData\Local\Google\Cloud SDK\google-cloud-sdk\platform\gsutil\gslib\__main__.py", line 785, in _RunNamedCommandAndHandleExceptions
    _HandleUnknownFailure(e)
  File "C:\Users\dandiazc\AppData\Local\Google\Cloud SDK\google-cloud-sdk\platform\gsutil\gslib\__main__.py", line 633, in _RunNamedCommandAndHandleExceptions
    return command_runner.RunNamedCommand(command_name,
  File "C:\Users\dandiazc\AppData\Local\Google\Cloud SDK\google-cloud-sdk\platform\gsutil\gslib\command_runner.py", line 421, in RunNamedCommand
    return_code = command_inst.RunCommand()
  File "C:\Users\dandiazc\AppData\Local\Google\Cloud SDK\google-cloud-sdk\platform\gsutil\gslib\commands\cp.py", line 1054, in RunCommand
    name_expansion_iterator = CopyObjectsIterator(
  File "C:\Users\dandiazc\AppData\Local\Google\Cloud SDK\google-cloud-sdk\platform\gsutil\gslib\name_expansion.py", line 677, in __init__
    name_expansion_dest_tuple = next(self.name_expansion_dest_iter)
  File "C:\Users\dandiazc\AppData\Local\Google\Cloud SDK\google-cloud-sdk\platform\gsutil\gslib\commands\cp.py", line 985, in _ConstructNameExpansionIteratorDstTupleIterator
    copy_helper.ExpandUrlToSingleBlr(dst_url_str,
  File "C:\Users\dandiazc\AppData\Local\Google\Cloud SDK\google-cloud-sdk\platform\gsutil\gslib\utils\copy_helper.py", line 1457, in ExpandUrlToSingleBlr
    for obj_or_prefix in list_iterator:
  File "C:\Users\dandiazc\AppData\Local\Google\Cloud SDK\google-cloud-sdk\platform\gsutil\gslib\gcs_json_api.py", line 812, in ListObjects
    object_list = self.api_client.objects.List(apitools_request,
  File "C:\Users\dandiazc\AppData\Local\Google\Cloud SDK\google-cloud-sdk\platform\gsutil\gslib\third_party\storage_apitools\storage_v1_client.py", line 1207, in List
    return self._RunMethod(
  File "C:\Users\dandiazc\AppData\Local\Google\Cloud SDK\google-cloud-sdk\platform\gsutil\third_party\apitools\apitools\base\py\base_api.py", line 734, in _RunMethod
    http_response = http_wrapper.MakeRequest(
  File "C:\Users\dandiazc\AppData\Local\Google\Cloud SDK\google-cloud-sdk\platform\gsutil\third_party\apitools\apitools\base\py\http_wrapper.py", line 359, in MakeRequest
    retry_func(ExceptionRetryArgs(http, http_request, e, retry,
  File "C:\Users\dandiazc\AppData\Local\Google\Cloud SDK\google-cloud-sdk\platform\gsutil\gslib\utils\retry_util.py", line 65, in WarnAfterManyRetriesHandler
    http_wrapper.HandleExceptionsAndRebuildHttpConnections(retry_args)
  File "C:\Users\dandiazc\AppData\Local\Google\Cloud SDK\google-cloud-sdk\platform\gsutil\third_party\apitools\apitools\base\py\http_wrapper.py", line 304, in HandleExceptionsAndRebuildHttpConnections
    raise retry_args.exc
  File "C:\Users\dandiazc\AppData\Local\Google\Cloud SDK\google-cloud-sdk\platform\gsutil\third_party\apitools\apitools\base\py\http_wrapper.py", line 348, in MakeRequest
    return _MakeRequestNoRetry(
  File "C:\Users\dandiazc\AppData\Local\Google\Cloud SDK\google-cloud-sdk\platform\gsutil\third_party\apitools\apitools\base\py\http_wrapper.py", line 397, in _MakeRequestNoRetry
    info, content = http.request(
  File "C:\Users\dandiazc\AppData\Local\Google\Cloud SDK\google-cloud-sdk\platform\gsutil\gslib\vendored\oauth2client\oauth2client\transport.py", line 159, in new_request
    credentials._refresh(orig_request_method)
  File "C:\Users\dandiazc\AppData\Local\Google\Cloud SDK\google-cloud-sdk\platform\gsutil\gslib\vendored\oauth2client\oauth2client\client.py", line 761, in _refresh
    self._do_refresh_request(http)
  File "C:\Users\dandiazc\AppData\Local\Google\Cloud SDK\google-cloud-sdk\platform\gsutil\third_party\google-reauth-python\google_reauth\reauth_creds.py", line 112, in _do_refresh_request
    self._update(*reauth.refresh_access_token(
  File "C:\Users\dandiazc\AppData\Local\Google\Cloud SDK\google-cloud-sdk\platform\gsutil\third_party\google-reauth-python\google_reauth\reauth.py", line 283, in refresh_access_token
    rapt = get_rapt_token(
  File "C:\Users\dandiazc\AppData\Local\Google\Cloud SDK\google-cloud-sdk\platform\gsutil\third_party\google-reauth-python\google_reauth\reauth.py", line 194, in get_rapt_token
    rapt_token = _obtain_rapt(
  File "C:\Users\dandiazc\AppData\Local\Google\Cloud SDK\google-cloud-sdk\platform\gsutil\third_party\google-reauth-python\google_reauth\reauth.py", line 142, in _obtain_rapt
    raise errors.ReauthUnattendedError()
google_reauth.errors.ReauthUnattendedError: Reauthentication challenge could not be answered because you are not in an interactive session.
Reauthentication required.
Traceback (most recent call last):
  File "C:\Users\dandiazc\AppData\Local\Google\Cloud SDK\google-cloud-sdk\platform\gsutil\gsutil", line 21, in <module>
    gsutil.RunMain()
  File "C:\Users\dandiazc\AppData\Local\Google\Cloud SDK\google-cloud-sdk\platform\gsutil\gsutil.py", line 151, in RunMain
    sys.exit(gslib.__main__.main())
  File "C:\Users\dandiazc\AppData\Local\Google\Cloud SDK\google-cloud-sdk\platform\gsutil\gslib\__main__.py", line 436, in main
    return _RunNamedCommandAndHandleExceptions(
  File "C:\Users\dandiazc\AppData\Local\Google\Cloud SDK\google-cloud-sdk\platform\gsutil\gslib\__main__.py", line 785, in _RunNamedCommandAndHandleExceptions
    _HandleUnknownFailure(e)
  File "C:\Users\dandiazc\AppData\Local\Google\Cloud SDK\google-cloud-sdk\platform\gsutil\gslib\__main__.py", line 633, in _RunNamedCommandAndHandleExceptions
    return command_runner.RunNamedCommand(command_name,
  File "C:\Users\dandiazc\AppData\Local\Google\Cloud SDK\google-cloud-sdk\platform\gsutil\gslib\command_runner.py", line 421, in RunNamedCommand
    return_code = command_inst.RunCommand()
  File "C:\Users\dandiazc\AppData\Local\Google\Cloud SDK\google-cloud-sdk\platform\gsutil\gslib\commands\cp.py", line 1054, in RunCommand
    name_expansion_iterator = CopyObjectsIterator(
  File "C:\Users\dandiazc\AppData\Local\Google\Cloud SDK\google-cloud-sdk\platform\gsutil\gslib\name_expansion.py", line 677, in __init__
    name_expansion_dest_tuple = next(self.name_expansion_dest_iter)
  File "C:\Users\dandiazc\AppData\Local\Google\Cloud SDK\google-cloud-sdk\platform\gsutil\gslib\commands\cp.py", line 985, in _ConstructNameExpansionIteratorDstTupleIterator
    copy_helper.ExpandUrlToSingleBlr(dst_url_str,
  File "C:\Users\dandiazc\AppData\Local\Google\Cloud SDK\google-cloud-sdk\platform\gsutil\gslib\utils\copy_helper.py", line 1457, in ExpandUrlToSingleBlr
    for obj_or_prefix in list_iterator:
  File "C:\Users\dandiazc\AppData\Local\Google\Cloud SDK\google-cloud-sdk\platform\gsutil\gslib\gcs_json_api.py", line 812, in ListObjects
    object_list = self.api_client.objects.List(apitools_request,
  File "C:\Users\dandiazc\AppData\Local\Google\Cloud SDK\google-cloud-sdk\platform\gsutil\gslib\third_party\storage_apitools\storage_v1_client.py", line 1207, in List
    return self._RunMethod(
  File "C:\Users\dandiazc\AppData\Local\Google\Cloud SDK\google-cloud-sdk\platform\gsutil\third_party\apitools\apitools\base\py\base_api.py", line 734, in _RunMethod
    http_response = http_wrapper.MakeRequest(
  File "C:\Users\dandiazc\AppData\Local\Google\Cloud SDK\google-cloud-sdk\platform\gsutil\third_party\apitools\apitools\base\py\http_wrapper.py", line 359, in MakeRequest
    retry_func(ExceptionRetryArgs(http, http_request, e, retry,
  File "C:\Users\dandiazc\AppData\Local\Google\Cloud SDK\google-cloud-sdk\platform\gsutil\gslib\utils\retry_util.py", line 65, in WarnAfterManyRetriesHandler
    http_wrapper.HandleExceptionsAndRebuildHttpConnections(retry_args)
  File "C:\Users\dandiazc\AppData\Local\Google\Cloud SDK\google-cloud-sdk\platform\gsutil\third_party\apitools\apitools\base\py\http_wrapper.py", line 304, in HandleExceptionsAndRebuildHttpConnections
    raise retry_args.exc
  File "C:\Users\dandiazc\AppData\Local\Google\Cloud SDK\google-cloud-sdk\platform\gsutil\third_party\apitools\apitools\base\py\http_wrapper.py", line 348, in MakeRequest
    return _MakeRequestNoRetry(
  File "C:\Users\dandiazc\AppData\Local\Google\Cloud SDK\google-cloud-sdk\platform\gsutil\third_party\apitools\apitools\base\py\http_wrapper.py", line 397, in _MakeRequestNoRetry
    info, content = http.request(
  File "C:\Users\dandiazc\AppData\Local\Google\Cloud SDK\google-cloud-sdk\platform\gsutil\gslib\vendored\oauth2client\oauth2client\transport.py", line 159, in new_request
    credentials._refresh(orig_request_method)
  File "C:\Users\dandiazc\AppData\Local\Google\Cloud SDK\google-cloud-sdk\platform\gsutil\gslib\vendored\oauth2client\oauth2client\client.py", line 761, in _refresh
    self._do_refresh_request(http)
  File "C:\Users\dandiazc\AppData\Local\Google\Cloud SDK\google-cloud-sdk\platform\gsutil\third_party\google-reauth-python\google_reauth\reauth_creds.py", line 112, in _do_refresh_request
    self._update(*reauth.refresh_access_token(
  File "C:\Users\dandiazc\AppData\Local\Google\Cloud SDK\google-cloud-sdk\platform\gsutil\third_party\google-reauth-python\google_reauth\reauth.py", line 283, in refresh_access_token
    rapt = get_rapt_token(
  File "C:\Users\dandiazc\AppData\Local\Google\Cloud SDK\google-cloud-sdk\platform\gsutil\third_party\google-reauth-python\google_reauth\reauth.py", line 194, in get_rapt_token
    rapt_token = _obtain_rapt(

^C

KeyboardInterrupt: